name = "pornhbu"
type = "javascript"
account_id = "ec7da0a1e1f36f7ad2c426e6b2d6fdaa"
workers_dev = false
route = "proxy.zztool.dpdns.org/*"  # 替换为你自己的域名
zone_id = "0dadc3a2e3598c78f742ce6645adeccb"    # 替换为你的 Cloudflare 区域 ID
